/**
 * Répertoire de phrases des quatre professeurs.
 *
 * Séparé de `professeurs.ts`, qui assemble les commentaires : ici il n'y a
 * que du texte, et c'est le volume qui compte. Un professeur qui redit la
 * même chose d'une partie à l'autre cesse d'être un personnage, et la
 * mémoire persistante (`memoirePhrases.ts`) ne sert à rien si les registres
 * sont trop courts pour qu'elle ait de quoi puiser.
 *
 * Ordre de grandeur retenu : au moins douze tournures par registre et par
 * professeur, soit de quoi tenir plusieurs parties complètes sans reprise.
 */

import type { MotifExplication } from './explications.ts';

/** Issue de la partie, du point de vue de l'ÉLÈVE. */
export type IssuePartie = 'victoire' | 'defaite' | 'nulle' | 'abandon';

/* --- Accueil --------------------------------------------------------------
   Une seule salutation par professeur ne tenait pas : trois parties de suite
   et l'illusion tombait. */
export const SALUTATIONS: Record<string, string[]> = {
  'homme-ultime': [
    'Asseyez-vous. Nous allons voir ce que vous savez faire.',
    'Bien. Montrez-moi votre jeu, je vous dirai ce qu’il vaut.',
    'Commençons. Je ne vous ménagerai pas, ce ne serait pas vous rendre service.',
    'À vous. Chaque coup compte, y compris le premier.',
    'Je regarde tout. Jouez comme si personne ne regardait.',
    'Une partie, et nous verrons où vous en êtes réellement.',
    'Prenez votre temps sur le premier coup. Il donne le ton.',
    'Nous y voilà. Pas d’excuses, pas de précipitation.',
    'Je vous écoute — par vos coups, s’entend.',
    'Allons-y. Ce qui m’intéresse, ce sont vos raisons, pas vos résultats.',
    'Vous avez les pièces, vous avez le trait. Faites-en quelque chose.',
    'Jouez. Je ne dirai rien tant qu’il n’y aura rien à dire.',
  ],
  ephraim: [
    'Bonjour. On va travailler dans l’ordre : le roi d’abord, la structure ensuite, la tactique en dernier.',
    'Bonjour. Une partie, et je commente chaque coup — ce qui tient et ce qui ne tient pas.',
    'On commence. Pensez « sécurité, structure, plan », toujours dans cet ordre.',
    'Bonjour. Ne cherchez pas le beau coup, cherchez le coup nécessaire.',
    'Prêt ? Je vous suis coup par coup, sans vous interrompre pour rien.',
    'Bonjour. Une bonne partie est une partie sans coup gratuit. Essayons.',
    'On y va. Le plan avant la combinaison, c’est la seule règle qui tienne.',
    'Bonjour. Je vous signalerai surtout ce qui se répète : c’est là qu’on progresse.',
    'Commençons proprement. Développez, mettez le roi à l’abri, puis regardez.',
    'Bonjour. Je préfère une partie solide à une partie brillante. Vous verrez pourquoi.',
    'On démarre. Dites-vous à chaque coup : qu’est-ce que ça change à ma position ?',
    'Bonjour. Je ne vous donnerai pas les coups, je vous donnerai les questions.',
  ],
  johana: [
    'Bonjour ! Installez-vous, on va passer un bon moment.',
    'Salut ! On joue, et je vous explique au fur et à mesure.',
    'Bonjour. Pas de pression : on est là pour apprendre, pas pour briller.',
    'Prête quand vous voulez. Jouez ce qui vous semble juste.',
    'Bonjour ! Dites-vous que chaque erreur est une leçon offerte.',
    'On commence ? Je vous accompagne à chaque coup.',
    'Bonjour. Je serai exigeante, mais toujours de votre côté.',
    'Allez, à vous. Faites-vous confiance.',
    'Bonjour ! J’aime bien les premiers coups, ils disent beaucoup.',
    'C’est parti. Prenez le temps de regarder toute la position.',
    'Bonjour. Si quelque chose vous échappe, je vous le montrerai.',
    'On y va. Et n’ayez pas peur de jouer un coup ambitieux.',
  ],
  serena: [
    'Bonjour. Installez-vous, j’ai toujours aimé ce moment d’avant la première pièce.',
    'Ah, une partie ! Rien ne vaut le silence d’un échiquier neuf.',
    'Bonjour. Vous savez, Capablanca disait que la partie commence avant le premier coup.',
    'Prenez place. Je vous préviens, je parle beaucoup, mais rarement pour rien.',
    'Bonjour. Une position de départ, c’est trente-deux promesses.',
    'Nous y sommes. J’espère que vous aimez les positions un peu désordonnées.',
    'Bonjour. Jouez ce qui vous plaît, on verra bien où cela nous mène.',
    'Enchantée de vous revoir devant un échiquier. Allons-y.',
    'Bonjour. J’ai un faible pour les débuts de partie — tout est encore possible.',
    'Asseyez-vous donc. Je commenterai, je digresserai, et parfois les deux.',
    'Bonjour. Le premier coup ne coûte rien, c’est le seul.',
    'Voilà. Faites comme chez vous, et jouez comme vous pensez.',
  ],
};

/* --- Fin de partie -------------------------------------------------------
   Défaut corrigé : une fois le mat tombé, le professeur continuait à
   commenter comme si le jeu se poursuivait. */
export const FIN_OUVERTURES: Record<string, Record<IssuePartie, string[]>> = {
  'homme-ultime': {
    victoire: [
      'Vous avez gagné. C’est ce qu’on attendait de vous.',
      'La partie est à vous. Bien.',
      'Victoire. Regardons comment vous l’avez obtenue.',
      'C’est fait. Vous avez tenu jusqu’au bout.',
      'Gagnée, et pas par accident.',
      'Voilà une partie menée à son terme.',
    ],
    defaite: [
      'Vous avez perdu. Ce n’est pas une catastrophe, c’est une leçon.',
      'Défaite. Nous allons voir où elle s’est jouée.',
      'C’est perdu. Regardez ce qui vous a coûté la partie.',
      'Vous avez cédé. Comprenez à quel moment.',
      'Battu. Reste à savoir pourquoi.',
      'La partie vous échappe. Ce n’est jamais un hasard.',
    ],
    nulle: [
      'Partie nulle. Ni gagnée, ni perdue.',
      'Match nul. Il y avait peut-être mieux à chercher.',
      'Nulle. La position ne donnait plus rien à personne.',
      'Partage. Voyons si vous avez laissé passer une occasion.',
    ],
    abandon: [
      'Vous abandonnez. C’est une décision, et elle se respecte.',
      'Abandon. Parfois c’est juste, parfois c’est prématuré.',
      'Vous rendez les armes. Voyons si c’était nécessaire.',
      'Partie abandonnée. Il faut savoir pourquoi on le fait.',
    ],
  },
  ephraim: {
    victoire: [
      'Partie gagnée. Reprenons ce qui a fonctionné.',
      'Vous l’emportez. Analysons la méthode.',
      'Victoire, et elle se construit. Voyons comment.',
      'C’est gagné. Le plan a tenu du début à la fin.',
      'Bien joué. Regardons la structure de cette partie.',
      'Vous gagnez. Retenons l’enchaînement.',
    ],
    defaite: [
      'Partie perdue. Nous allons la démonter proprement.',
      'Défaite. Cherchons le moment où le plan a lâché.',
      'Vous perdez cette partie. Il y a une cause, et elle est identifiable.',
      'C’est perdu. La bonne nouvelle, c’est que la cause se voit.',
      'Revers. Regardons la structure avant la tactique.',
      'Partie perdue. Ce n’est pas grave si on en tire la règle.',
    ],
    nulle: [
      'Partie nulle. L’équilibre a tenu.',
      'Match nul. Correct, sans plus.',
      'Nulle. Les deux camps ont manqué le moment décisif.',
      'Partage du point. Voyons s’il y avait mieux.',
    ],
    abandon: [
      'Vous abandonnez. Regardons si la position le justifiait.',
      'Abandon. C’est parfois la bonne décision, parfois une facilité.',
      'Vous arrêtez la partie. Analysons la position au moment où vous l’avez quittée.',
      'Partie abandonnée. Voyons ce qu’il restait à défendre.',
    ],
  },
  johana: {
    victoire: [
      'Bravo, vous avez gagné !',
      'Victoire, et vous l’avez méritée.',
      'Gagné ! Je savais que vous pouviez y arriver.',
      'C’est une belle victoire. Profitez-en.',
      'Vous l’avez fait. Très bien.',
      'Partie gagnée, et proprement.',
    ],
    defaite: [
      'C’est perdu, et ce n’est pas grave. On regarde ensemble.',
      'Défaite. Ne baissez pas la tête, on va comprendre.',
      'Vous avez perdu celle-là. C’est comme ça qu’on progresse.',
      'Partie perdue. Ce qui compte, c’est ce que vous en tirez.',
      'C’est raté cette fois. La prochaine sera différente.',
      'Battu, mais vous avez tenu longtemps.',
    ],
    nulle: [
      'Partie nulle. C’est un résultat honnête.',
      'Match nul. Vous n’avez rien lâché.',
      'Nulle. Il y avait peut-être un peu plus à aller chercher.',
      'Partage. Pas de quoi rougir.',
    ],
    abandon: [
      'Vous abandonnez. On va regarder si c’était vraiment perdu.',
      'Abandon. Parfois il faut savoir s’arrêter, parfois il faut s’accrocher.',
      'Vous arrêtez. Voyons ce qu’il restait comme ressources.',
      'Partie abandonnée. Ne prenez pas l’habitude trop vite.',
    ],
  },
  serena: {
    victoire: [
      'Vous avez gagné, et c’est très bien ainsi.',
      'Victoire ! Voyons comment elle est venue.',
      'Gagnée. Il y a eu un joli moment dans cette partie.',
      'C’est à vous. Bien mené.',
      'Belle partie, et belle fin.',
      'Vous l’emportez. Reprenons le fil.',
    ],
    defaite: [
      'Perdue. Cela arrive aux meilleurs, et régulièrement.',
      'Défaite. Ce n’est pas la fin du monde, loin de là.',
      'Vous perdez cette partie. Regardons-la sans amertume.',
      'C’est perdu, et il y avait pourtant de bonnes idées.',
      'Battu. Reprenons calmement.',
      'Partie perdue. Il y a toujours quelque chose à y prendre.',
    ],
    nulle: [
      'Partie nulle. L’équilibre a résisté.',
      'Match nul. Un résultat qui se défend.',
      'Nulle. Personne n’a trouvé la faille.',
      'Partage. C’est parfois le plus juste.',
    ],
    abandon: [
      'Vous abandonnez. Voyons si la position le méritait.',
      'Abandon. Une décision qui en dit long sur la position.',
      'Vous quittez la partie. Regardons où elle en était.',
      'Partie abandonnée. On en tire quand même quelque chose.',
    ],
  },
};

/** Comment introduire le coup qui a fait basculer la partie. */
export const FIN_PIVOT: Record<string, string[]> = {
  'homme-ultime': [
    'Tout s’est joué sur',
    'La partie bascule à',
    'Le point de rupture est',
    'C’est à ce coup que tout change :',
    'Retenez ce moment :',
  ],
  ephraim: [
    'Le moment décisif est',
    'La partie change de nature à',
    'Le basculement se situe à',
    'C’est là que la structure cède :',
    'Le coup à revoir est',
  ],
  johana: [
    'Le coup qui a tout changé, c’est',
    'Regardez bien ce moment :',
    'C’est là que ça s’est joué :',
    'Le tournant, c’est',
    'Notez ce coup-là :',
  ],
  serena: [
    'Le moment charnière, c’est',
    'Tout tient à ce coup :',
    'La partie pivote à',
    'C’est ici que la balance penche :',
    'Le coup à retenir est',
  ],
};

/** Ce qu'il faut retenir, selon l'issue. */
export const FIN_CONSEIL: Record<string, Record<'gagne' | 'perdu', string[]>> = {
  'homme-ultime': {
    gagne: [
      'Retenez la méthode, pas le résultat. Le résultat ne se répète pas, la méthode si.',
      'Une victoire ne prouve rien si vous ne savez pas dire pourquoi.',
      'Gardez cette rigueur quand vous serez moins bien placé.',
      'La prochaine sera plus dure. Préparez-vous en conséquence.',
      'Ne confondez pas avoir gagné et avoir bien joué.',
    ],
    perdu: [
      'Une partie perdue vaut trois parties gagnées, si vous la relisez.',
      'Ne cherchez pas d’excuse dans la position. Cherchez le coup.',
      'Vous saurez éviter cela la prochaine fois. C’est tout ce qu’on demande.',
      'Perdre n’est rien. Perdre deux fois de la même manière, si.',
      'Revoyez ce coup à froid. Vous le verrez venir la prochaine fois.',
    ],
  },
  ephraim: {
    gagne: [
      'Notez l’ordre dans lequel vous avez procédé : c’est lui qui a gagné.',
      'Refaites ce plan dans une autre partie, vous verrez qu’il tient.',
      'La solidité paie. Continuez ainsi.',
      'Votre structure a tenu jusqu’au bout, c’est l’essentiel.',
      'Une victoire méthodique vaut mieux qu’une victoire chanceuse.',
    ],
    perdu: [
      'Reprenez cette partie au calme et cherchez le coup où le plan s’est interrompu.',
      'La faute n’est presque jamais là où l’on croit : elle précède la perte de matériel.',
      'Travaillez la position, pas la tactique. Elle viendra d’elle-même.',
      'Une défaite bien analysée ne se reproduit pas.',
      'Identifiez la question que vous ne vous êtes pas posée.',
    ],
  },
  johana: {
    gagne: [
      'Vous progressez, ça se voit dans cette partie.',
      'Gardez cette confiance, elle vous va bien.',
      'Continuez comme ça, vous êtes sur la bonne voie.',
      'Belle maîtrise. Faites-en une habitude.',
      'Vous avez tenu votre plan, c’est ça le plus dur.',
    ],
    perdu: [
      'Ne retenez pas la défaite, retenez le coup qui l’a causée.',
      'Vous avez bien joué par moments, c’est ça qu’il faut garder.',
      'On rejoue quand vous voulez. C’est comme ça qu’on apprend.',
      'Une partie perdue, c’est une leçon gratuite. Prenez-la.',
      'Vous y étiez presque. Ne lâchez rien.',
    ],
  },
  serena: {
    gagne: [
      'Savourez, puis relisez. Les victoires enseignent moins, mais elles enseignent.',
      'Il y avait de vraies idées là-dedans. Gardez-les.',
      'Capablanca disait qu’on apprend surtout de ses défaites. Il gagnait beaucoup, cela dit.',
      'Une belle partie. Refaites-la de mémoire ce soir, vous verrez ce qui reste.',
      'Le plaisir d’une partie gagnée est un excellent professeur, à petite dose.',
    ],
    perdu: [
      'Les meilleures parties de l’histoire ont été perdues par quelqu’un.',
      'Reprenez-la demain, à froid. Vous y verrez des choses invisibles aujourd’hui.',
      'Une défaite comprise vaut mieux qu’une victoire subie.',
      'Ce n’est qu’une partie. Il y en aura d’autres, et vous serez meilleur.',
      'Tartakover prétendait que personne n’a jamais gagné en abandonnant. Il exagérait à peine.',
    ],
  },
};

/** Manière de saluer un beau coup dans le bilan de fin de partie. */
export const FIN_BEAU_COUP: Record<string, string[]> = {
  'homme-ultime': [
    'Votre meilleur moment :',
    'À mettre à votre crédit :',
    'Un coup juste, celui-là :',
  ],
  ephraim: [
    'Ce que vous avez bien fait :',
    'Le bon moment de la partie :',
    'À retenir du côté positif :',
  ],
  johana: [
    'Et votre plus beau coup :',
    'Ça, c’était très bien vu :',
    'Gardez ce moment-là :',
  ],
  serena: [
    'Il y a eu ce joli coup :',
    'Votre meilleur instant :',
    'Et ce coup-là m’a plu :',
  ],
};

/** Motifs pour lesquels un conseil de fin de partie existe. */
export const LECON_MOTIF: Partial<Record<MotifExplication, string>> = {
  'piece-en-prise': 'comptez les attaquants et les défenseurs avant de poser une pièce',
  'menace-ignoree': 'demandez-vous à chaque coup adverse ce qu’il menace',
  fourchette: 'surveillez les cases d’où un cavalier toucherait deux pièces à la fois',
  clouage: 'évitez d’aligner une pièce et votre roi sur une même ligne',
  enfilade: 'ne laissez pas deux pièces de valeur sur une même ligne',
  'mat-manque': 'quand le roi adverse étouffe, cherchez le mat avant le matériel',
  'mat-subi': 'comptez les cases de fuite de votre roi avant d’ouvrir une ligne',
  'occasion-manquee': 'avant de consolider, vérifiez s’il n’y a pas un coup qui gagne tout de suite',
};

/**
 * Réaction du professeur au coup, en quelques mots.
 *
 * Quatre tons — le bon coup, l'imprécision, la faute lourde, le coup attendu —
 * et vingt à vingt-huit tournures par ton et par professeur.
 *
 * Ce volume n'est pas de la coquetterie. La règle est qu'une phrase ne revient
 * jamais dans une partie tant qu'il reste des variantes : un registre doit donc
 * contenir au moins autant de tournures que la partie comptera d'occasions de
 * s'en servir. Une partie de quarante coups produit une vingtaine de bons
 * coups, une quinzaine d'imprécisions et quelques fautes lourdes — d'où ces
 * comptes, et non un chiffre rond.
 *
 * Les quatre ne disent jamais la même chose dans la même situation : le
 * souverain constate, l'entraîneur rapporte à la structure, l'exigeante
 * encourage ou gronde, l'érudite situe.
 */
export const REACTIONS: Record<string, Record<'bon' | 'faute' | 'grave' | 'neutre', string[]>> = {
  'homme-ultime': {
    bon: [
      'Correct.',
      'C’est le coup.',
      'Vous voyez juste.',
      'Rien à reprendre.',
      'Voilà le niveau que j’attends.',
      'Exact.',
      'C’est ainsi qu’on joue.',
      'Bien vu.',
      'Tenez cette rigueur.',
      'Le bon choix.',
      'Vous progressez.',
      'Cela se défend.',
      'Juste.',
      'C’est le coup qu’il fallait.',
      'Sans reproche.',
      'Vous avez compris.',
      'Propre.',
      'Je n’ai rien à dire.',
      'Voilà de la volonté.',
      'C’est digne.',
      'Vous tenez la barre.',
      'Solide.',
      'Bien pesé.',
      'Vous ne tremblez pas.',
      'Ferme.',
      'Voilà une main sûre.',
      'Je prends note.',
      'C’est le coup d’un joueur sérieux.',
    ],
    faute: [
      'Imprécis.',
      'Ce n’est pas le coup.',
      'Vous hésitez.',
      'Approximatif.',
      'Cela se paiera.',
      'Trop mou.',
      'Vous relâchez.',
      'Insuffisant.',
      'Vous perdez du terrain.',
      'Mal pesé.',
      'Vous reculez.',
      'Ce n’est pas sérieux.',
      'Vous laissez filer.',
      'Tiède.',
      'Vous manquez de nerf.',
      'Discutable.',
      'Vous vous dispersez.',
      'Faute de jugement.',
      'Vous baissez la garde.',
      'Léger.',
      'Vous cédez l’initiative.',
      'Médiocre.',
      'Vous n’y êtes pas.',
      'Reprenez-vous.',
    ],
    grave: [
      'C’est une faute lourde.',
      'Vous venez de perdre la partie.',
      'Inacceptable.',
      'Tout s’écroule.',
      'Vous abandonnez la position.',
      'C’est grave.',
      'Vous vous êtes puni vous-même.',
      'La partie vous échappe.',
      'Rien ne tient plus.',
      'Vous avez tout défait.',
      'C’est une catastrophe.',
      'Vous venez de tout rendre.',
      'La position est ruinée.',
      'Vous avez cédé.',
      'Faute capitale.',
      'Vous vous êtes livré.',
      'C’est un désastre.',
      'Vous perdez pied.',
      'La sanction sera immédiate.',
      'Vous venez de tout gâcher.',
    ],
    neutre: [
      'C’est la ligne connue.',
      'Attendu.',
      'On reste dans les livres.',
      'Rien de neuf.',
      'La théorie, donc.',
      'Classique.',
      'On suit le chemin tracé.',
      'Convenu.',
      'Soit.',
      'Je connais la suite.',
      'C’est le coup des maîtres.',
      'Sans surprise.',
      'La route est balisée.',
      'Vous récitez.',
      'Admis.',
      'Nous en sommes aux préliminaires.',
      'C’est écrit depuis longtemps.',
      'Passons.',
      'Rien à commenter ici.',
      'Nous verrons plus loin.',
    ],
  },
  ephraim: {
    bon: [
      'Bien joué.',
      'C’est dans l’ordre.',
      'La structure tient.',
      'Bon choix.',
      'C’est logique.',
      'Vous développez juste.',
      'C’est exact.',
      'Le roi gagne en sécurité.',
      'Vous gardez la cohérence.',
      'Voilà un coup utile.',
      'Rien ne traîne.',
      'Vous occupez le centre.',
      'C’est propre.',
      'Vous suivez le plan.',
      'Bonne coordination.',
      'Les pièces se parlent.',
      'C’est méthodique.',
      'Vous gagnez un temps.',
      'La position s’améliore.',
      'Vous consolidez.',
      'Vous voyez la case.',
      'Rien à redire.',
      'C’est le coup utile.',
      'Vous avancez d’un cran.',
      'Vous respectez l’ordre.',
      'Bonne tenue.',
      'C’est sain.',
      'Vous construisez.',
    ],
    faute: [
      'Ce n’est pas l’ordre.',
      'Vous brûlez une étape.',
      'Attention à la structure.',
      'C’est imprécis.',
      'Le roi reste exposé.',
      'Vous perdez un temps.',
      'Ce coup ne sert à rien.',
      'Vous dégarnissez.',
      'Il y avait plus utile.',
      'La coordination se défait.',
      'Vous jouez à l’envers.',
      'C’est prématuré.',
      'Vous laissez une faiblesse.',
      'Pas encore ce coup-là.',
      'Vous oubliez le roi.',
      'Ce n’est pas le moment.',
      'Vous reculez d’un cran.',
      'La case faible va compter.',
      'Vous perdez la cohérence.',
      'Trop tôt.',
      'Vous jouez sans plan.',
      'Il manquait un coup avant.',
      'Vous affaiblissez les pions.',
      'Revenons à l’ordre.',
    ],
    grave: [
      'Là, c’est une faute lourde.',
      'La structure s’effondre.',
      'Vous perdez du matériel.',
      'C’est lourd.',
      'Le roi est à découvert.',
      'Tout se défait.',
      'Vous donnez la pièce.',
      'La position casse.',
      'C’est une erreur de fond.',
      'Vous laissez entrer l’adversaire.',
      'Le plan est ruiné.',
      'C’est une rupture.',
      'Vous ouvrez votre camp.',
      'La faiblesse devient décisive.',
      'Vous perdez l’échange.',
      'C’est une faute de principe.',
      'Le roi ne tiendra pas.',
      'Vous cassez tout.',
      'La coordination est perdue.',
      'C’est le coup qui coûte la partie.',
    ],
    neutre: [
      'C’est la ligne principale.',
      'On est dans la théorie.',
      'Coup de livre.',
      'Dans l’ordre.',
      'Rien d’imprévu.',
      'On suit le plan classique.',
      'Rien d’inhabituel.',
      'C’est la suite logique.',
      'Bon ordre.',
      'On développe.',
      'C’est la voie principale.',
      'Sans histoire.',
      'On prépare.',
      'Rien à signaler.',
      'C’est le schéma habituel.',
      'On progresse dans l’ordre.',
      'Position connue.',
      'La théorie dit ceci.',
      'Jusqu’ici, tout est écrit.',
      'On continue le développement.',
    ],
  },
  johana: {
    bon: [
      'Très bien !',
      'Oui, exactement !',
      'Bravo.',
      'C’est ça !',
      'Parfait.',
      'Vous l’avez vu !',
      'Excellent.',
      'Bien joué !',
      'Voilà, c’est ça.',
      'Super.',
      'Vous progressez !',
      'J’aime ce coup.',
      'Vous avez regardé, bien.',
      'Contente de voir ça.',
      'C’est exactement l’idée.',
      'Oui !',
      'Vous tenez le bon bout.',
      'Joli.',
      'Vous gagnez en sûreté.',
      'Ça me plaît.',
      'Vous avez compris le truc.',
      'Impeccable.',
      'Vous jouez juste.',
      'Continuez comme ça !',
      'Vous y êtes.',
      'Belle idée.',
      'Bien vu !',
      'Voilà du bon travail.',
    ],
    faute: [
      'Attention.',
      'Hmm, pas tout à fait.',
      'Regardez mieux.',
      'Ce n’est pas ça.',
      'Doucement.',
      'Vous allez trop vite.',
      'Pas encore.',
      'Attention à ce coup.',
      'Vous avez oublié quelque chose.',
      'Regardez l’adversaire.',
      'Ce n’était pas le moment.',
      'Presque.',
      'Il y avait mieux.',
      'Vous perdez un peu de terrain.',
      'Pas comme ça.',
      'Reprenez votre souffle.',
      'Vous jouez sans regarder.',
      'Ce coup vous coûte.',
      'Il faut compter avant.',
      'Pas l’idée.',
      'Vous laissez une prise.',
      'Vous allez le regretter.',
      'On y revient.',
      'Regardez encore.',
    ],
    grave: [
      'Oh là, non !',
      'Là, ça fait mal.',
      'Aïe.',
      'Ce coup coûte très cher.',
      'Non, pas ça !',
      'Vous venez de perdre une pièce.',
      'C’est une grosse erreur.',
      'Attention, c’est grave.',
      'Oups.',
      'Vous donnez tout.',
      'Là, c’est la partie qui part.',
      'Non !',
      'Vous vous êtes fait prendre.',
      'Grosse faute.',
      'C’était à éviter absolument.',
      'Là, il faut s’arrêter.',
      'Vous avez tout donné.',
      'Dommage, vraiment.',
      'C’est le coup qui perd.',
      'On ne refait pas celui-là.',
    ],
    neutre: [
      'D’accord.',
      'C’est connu, ça.',
      'Classique !',
      'Bon début.',
      'On continue.',
      'C’est un coup de livre.',
      'Rien d’étonnant.',
      'Ça se joue beaucoup.',
      'Très bien.',
      'On avance.',
      'C’est la suite normale.',
      'Ça marche.',
      'Pas de surprise.',
      'On est encore dans l’ouverture.',
      'Allons-y.',
      'C’est du connu.',
      'Bien, on suit.',
      'Rien à dire ici.',
      'On déroule.',
      'C’est le début habituel.',
    ],
  },
  serena: {
    bon: [
      'Joliment joué.',
      'Voilà un beau coup.',
      'Oui, c’est cela.',
      'Élégant.',
      'Très juste.',
      'C’est le coup des bons joueurs.',
      'Charmant.',
      'Vous avez l’œil.',
      'Bien senti.',
      'C’est fin.',
      'Voilà de la clarté.',
      'Vous jouez avec goût.',
      'Exactement.',
      'C’est ce qu’aurait joué Capablanca.',
      'Bien pensé.',
      'La position respire.',
      'Juste et net.',
      'Vous voyez loin.',
      'C’est harmonieux.',
      'Belle main.',
      'Voilà du métier.',
      'Cela me plaît beaucoup.',
      'Vous avez saisi l’idée.',
      'C’est le coup naturel.',
      'Propre et net.',
      'Vous jouez posément.',
      'Voilà ce qu’il fallait.',
      'Bravo, sincèrement.',
    ],
    faute: [
      'Hmm.',
      'Pas tout à fait.',
      'C’est un peu flou.',
      'Attention, là.',
      'Ce coup manque de suite.',
      'Voyons autrement.',
      'Il y avait plus clair.',
      'C’est dommage.',
      'Vous perdez le fil.',
      'Un peu mou.',
      'Ce n’est pas le plus précis.',
      'Je ne suis pas convaincue.',
      'La position vous le reprochera.',
      'Un peu léger.',
      'Trop pressé.',
      'Ce coup ne dit rien.',
      'Vous cédez un peu.',
      'Ce n’était pas nécessaire.',
      'Ce n’est pas net.',
      'Vous laissez du jeu.',
      'Il manquait un regard.',
      'Vous vous compliquez la vie.',
      'Reprenons le fil.',
      'Ce n’est pas le plus élégant.',
    ],
    grave: [
      'Oh.',
      'Là, c’est sérieux.',
      'C’est une faute grave.',
      'Aïe aïe aïe.',
      'Vous perdez beaucoup.',
      'C’est très coûteux.',
      'La position se retourne.',
      'Mon dieu.',
      'Vous donnez trop.',
      'C’est une rupture nette.',
      'Tout change ici.',
      'C’est le coup qui coûte.',
      'Vous venez de tout offrir.',
      'Quel dommage.',
      'La partie basculait là.',
      'C’est une lourde erreur.',
      'Vous perdez la pièce.',
      'Il fallait absolument autre chose.',
      'C’est un accident.',
      'La position ne pardonne pas ça.',
    ],
    neutre: [
      'Voilà la théorie.',
      'C’est une ligne connue.',
      'On la joue depuis un siècle.',
      'Très classique.',
      'Rien de neuf sous le soleil.',
      'C’est le chemin habituel.',
      'On suit les maîtres.',
      'On s’y attendait.',
      'Bien, on avance.',
      'C’est dans tous les livres.',
      'Rien d’inattendu.',
      'La bibliothèque est d’accord.',
      'Nous continuons.',
      'C’est le début connu.',
      'Pas de quoi s’arrêter.',
      'La suite normale.',
      'On déroule l’ouverture.',
      'Rien à redire ici.',
      'C’est la grande route.',
      'Nous verrons plus tard.',
    ],
  },
};

/**
 * Réponse au choix « reprendre le coup ».
 *
 * Douze par professeur, comme les autres registres : celui-ci tombe une fois
 * par coup repris, donc plusieurs fois par partie. À trois variantes, la
 * troisième partie n'en avait plus de neuves et le professeur se répétait.
 */
export const REPRISE_ACCORDEE: Record<string, string[]> = {
  'homme-ultime': [
    'Bien. Rejouez, et réfléchissez cette fois.',
    'On reprend. Faites mieux.',
    'Soit. Recommencez.',
    'Accordé. Ne refaites pas le même.',
    'Reprenez. Cette fois, comptez.',
    'Va pour la reprise. Regardez d’abord.',
    'On efface. Mais on n’efface pas la raison.',
    'Entendu. La position n’a pas changé, elle.',
    'Reprenez donc. Je vous attends.',
    'Deuxième essai. Il vaut mieux qu’il serve.',
    'Bien. Un coup reprisé est un coup compris.',
    'Soit. Prenez le temps, cette fois.',
  ],
  ephraim: [
    'D’accord, on reprend.',
    'Très bien, rejouez ce coup.',
    'On revient en arrière. Regardez la position.',
    'Reprenez. Prenez le temps qu’il faut.',
    'Volontiers. Reconsidérez tranquillement.',
    'On efface. Reprenons depuis la position.',
    'Entendu. Que voyez-vous d’autre ?',
    'Accordé. Relisez la position avant de jouer.',
    'Bien sûr. Un coup repris, c’est un coup examiné.',
    'On revient. Cherchez le coup qui tient.',
    'D’accord. Reprenez sans vous presser.',
    'Très bien. La bonne idée est souvent la deuxième.',
  ],
  johana: [
    'D’accord, on reprend !',
    'Bonne idée, rejouez-le.',
    'On efface, à vous.',
    'Oui, reprenez !',
    'Pas de souci, on recommence.',
    'Allez-y, une autre fois.',
    'On annule, à vous de jouer.',
    'Très bien, deuxième essai !',
    'Ça arrive ! Reprenez.',
    'Avec plaisir, rejouez.',
    'On revient en arrière, tranquille.',
    'Bien vu de reprendre. Allez-y !',
  ],
  serena: [
    'On reprend, volontiers.',
    'Très bien, revenons en arrière.',
    'D’accord, rejouez.',
    'Reprenons. Rien n’est perdu.',
    'Bien sûr, on efface.',
    'Entendu. Regardez encore.',
    'Volontiers. Le tableau reste ouvert.',
    'On revient. Prenez votre temps.',
    'D’accord. Cherchez la ligne plus juste.',
    'Reprenez donc, c’est de bon sens.',
    'Très bien. Un coup se médite.',
    'Accordé. Écoutez la position.',
  ],
};


/**
 * Ce que dit le professeur quand l'élève enchaîne les coups.
 *
 * Une ligne, pas un paragraphe : à moins de deux secondes par coup, personne ne
 * lit trois phrases. Vingt-quatre par professeur, parce qu'une partie jouée vite
 * en consomme autant — et qu'aucune ne doit revenir.
 *
 * Ce registre remplace l'ancien « interrompu », qui existait pour une seule
 * raison : la voix. Quand le professeur parlait encore et que l'élève jouait, il
 * reconnaissait le coup avant d'enchaîner — « Ah, vous avez joué ça. » La voix
 * est partie, et avec elle la raison d'être de cette formule, qui revenait coup
 * après coup et s'entendait comme un tic.
 */
export const BREVES: Record<string, string[]> = {
  'homme-ultime': [
    'Vu.',
    'Soit.',
    'Je suis.',
    'Admis.',
    'Je garde l’œil.',
    'Suivant.',
    'Pas d’objection.',
    'Vous allez vite.',
    'Soit, poursuivez.',
    'C’est entendu.',
    'Rien d’alarmant.',
    'Tenez le cap.',
    'J’observe.',
    'Pour l’instant, oui.',
    'Sans reproche.',
    'Avancez.',
    'Je me tais, jouez.',
    'Rien à reprendre ici.',
    'Vous tenez.',
    'Je laisse courir.',
    'Cela peut passer.',
    'J’attends la suite.',
    'Rien de décisif.',
    'Poursuivez donc.',
    'Rien à ajouter.',
    'Cela tiendra.',
    'Je vous laisse faire.',
    'Vous êtes dans le vrai.',
    'Rien ne m’inquiète.',
    'Bien, la suite.',
    'Je vous regarde.',
    'Aucune remarque.',
    'Vous gardez la main.',
    'C’est acceptable.',
    'Rien ne presse.',
    'Allez au bout.',
  ],
  ephraim: [
    'La structure tient.',
    'Rien ne casse.',
    'On enchaîne.',
    'C’est jouable.',
    'Rien d’urgent.',
    'Bon.',
    'Ça se tient.',
    'La suite.',
    'Correct, la suite.',
    'Rien à signaler.',
    'On garde le cap.',
    'Le plan tient.',
    'Rien d’important ici.',
    'On continue dans l’ordre.',
    'Pas de faiblesse.',
    'Cela se défend.',
    'Je note le coup.',
    'Rien à corriger.',
    'La position tient.',
    'On avance d’un cran.',
    'Pas d’erreur.',
    'C’est cohérent.',
    'Je suis le fil.',
    'On poursuit.',
    'Les pièces tiennent.',
    'Pas de trou.',
    'Le roi est sûr.',
    'Rien ne bouge en mal.',
    'C’est tenable.',
    'On reste cohérent.',
    'Pas de perte.',
    'La coordination tient.',
    'Rien à reprendre.',
    'C’est dans le plan.',
    'On ne perd rien.',
    'La suite, donc.',
  ],
  johana: [
    'Oui !',
    'Ça marche.',
    'Je suis !',
    'Allez !',
    'Pas de souci.',
    'On enchaîne !',
    'Super.',
    'Continuez !',
    'Vous filez !',
    'Ça me va.',
    'Je vous regarde faire.',
    'Bien joué, vite !',
    'Pas de bêtise.',
    'Ça roule.',
    'On y est !',
    'Vous êtes lancé !',
    'Rien de méchant.',
    'Allez-y !',
    'C’est bon.',
    'Vous gérez.',
    'Je ne dis rien, continuez !',
    'Oui, ça passe.',
    'Tenez le rythme !',
    'Impeccable, vite.',
    'Nickel.',
    'Ça tient bien !',
    'Vous êtes dedans !',
    'Rien à signaler, allez !',
    'Ça avance !',
    'Joli rythme !',
    'Vous tenez bon.',
    'Pas d’inquiétude.',
    'C’est tout bon.',
    'Vous enchaînez bien !',
    'Rien de cassé.',
    'Encore un !',
  ],
  serena: [
    'Je vous suis.',
    'Bien.',
    'Noté.',
    'Joli.',
    'Je regarde.',
    'Oui.',
    'Poursuivons.',
    'Très bien.',
    'Entendu.',
    'Parfait.',
    'Rien de grave.',
    'Allons-y.',
    'Rien d’inquiétant.',
    'Ça passe.',
    'Je prends note.',
    'Continuons ainsi.',
    'Vous allez bon train.',
    'Je ne vous arrête pas.',
    'Cela se tient.',
    'Bien, bien.',
    'Rien à redire ici.',
    'Je laisse dire.',
    'Oui, continuez.',
    'C’est noté.',
    'Fort bien.',
    'Cela se laisse jouer.',
    'Je ne dis mot.',
    'Rien ne me trouble.',
    'Vous tenez votre ligne.',
    'C’est raisonnable.',
    'Je vous accompagne.',
    'Rien d’important.',
    'Cela se tient fort bien.',
    'Poursuivez, je suis là.',
    'Aucune objection.',
    'Soit, la suite.',
  ],
};

/** Les trois temps d'une partie. */
export type PhasePartie = 'ouverture' | 'milieu' | 'finale';

/**
 * Ce que le professeur a à dire du moment de la partie.
 *
 * Une partie équilibrée ne donne rien à annoncer — ni « vous êtes gagnant », ni
 * « c’est perdu » — et le commentaire se réduisait alors à la réaction et au
 * coup. Ces remarques occupent cette place : elles enseignent le temps de la
 * partie où l'on se trouve, qui n'est pas le même selon qu'on développe, qu'on
 * manœuvre ou qu'on pousse un pion passé.
 *
 * Douze par phase et par professeur : une partie passe au plus une dizaine de
 * coups posés dans chaque phase.
 */
export const PHASES: Record<string, Record<PhasePartie, string[]>> = {
  'homme-ultime': {
    ouverture: [
      'En ouverture, on prend ou on cède. Il n’y a pas de troisième voie.',
      'Les premiers coups décident du reste. Ne les jouez pas distraitement.',
      'Un roi mal placé en ouverture se paie trente coups plus tard.',
      'L’ouverture n’est pas un rituel, c’est une prise de position.',
      'Développez, mais développez vers quelque chose.',
      'Le centre se prend tôt, ou ne se prend pas.',
      'Je juge une ouverture à ce qu’elle promet, pas à son nom.',
      'Chaque pion avancé est un pion qui ne revient pas.',
      'Les débuts pardonnent moins qu’on ne le dit.',
      'Posez vos pièces où elles menacent, pas où elles dorment.',
      'Une ouverture sans plan est une ouverture perdue.',
      'Ne jouez pas pour éviter la faute. Jouez pour imposer.',
    ],
    milieu: [
      'Au milieu de partie, le plan compte plus que le coup.',
      'Ici, l’initiative change de camp à chaque imprécision.',
      'On ne gagne pas un milieu de partie par accident.',
      'Trouvez la faiblesse adverse, puis frappez-la deux fois.',
      'Les pièces inactives sont des pièces perdues.',
      'Le milieu de partie récompense ceux qui osent.',
      'Une position fermée ne se force pas, elle se prépare.',
      'Comptez avant de prendre. Toujours.',
      'Le roi adverse est une adresse, pas un décor.',
      'Ne déplacez pas une pièce pour la déplacer.',
      'Celui qui attend se fait dicter la partie.',
      'Deux menaces valent mieux qu’une belle idée.',
    ],
    finale: [
      'En finale, on ne bluffe plus. On compte.',
      'Le roi devient une pièce d’attaque. Utilisez-le.',
      'Un pion passé est une menace permanente.',
      'Les finales se gagnent avec les pieds, pas avec les mains.',
      'L’activité vaut mieux que le matériel, en finale.',
      'Une case gagnée en finale vaut une pièce en milieu de partie.',
      'Ici, la précision remplace l’imagination.',
      'Poussez le pion qui n’a personne devant lui.',
      'En finale, la patience est une arme.',
      'Comptez les tempos. Ils décident tout.',
      'Une tour passive en finale, c’est une tour en moins.',
      'Le dernier qui se trompe perd. Ne vous trompez pas.',
    ],
  },
  ephraim: {
    ouverture: [
      'En ouverture : le roi d’abord, le centre ensuite, la tactique en dernier.',
      'Développez une pièce par coup, sans revenir en arrière.',
      'Ne sortez pas la dame trop tôt, elle se fait chasser.',
      'Trois coups de pions suffisent dans l’ouverture. Pas plus.',
      'Chaque pièce vers une case utile, et une seule fois.',
      'Le roque est un coup de développement, pas un luxe.',
      'Occupez le centre avant de chercher les ailes.',
      'Une ouverture réussie, c’est une position sans trou.',
      'Comptez vos tempos : l’ouverture est une course.',
      'Reliez vos tours, c’est le signe que l’ouverture est finie.',
      'Un pion qui avance laisse une case derrière lui. Sachez laquelle.',
      'Ne cherchez pas de tactique avant d’avoir développé.',
    ],
    milieu: [
      'Au milieu de partie, cherchez la case faible et installez-vous dessus.',
      'Un plan clair vaut mieux que trois coups brillants.',
      'Améliorez votre pièce la plus mal placée.',
      'Les colonnes ouvertes appartiennent aux tours.',
      'Avant d’attaquer, vérifiez que votre roi est à l’abri.',
      'Échangez quand vous êtes à l’étroit, gardez quand vous êtes au large.',
      'La structure de pions dicte le plan. Lisez-la.',
      'Doublez vos tours avant d’ouvrir la colonne.',
      'Ne cassez le centre que si vous y gagnez une case.',
      'Chaque coup doit répondre à : qu’est-ce que cela améliore ?',
      'Un cavalier sur une case protégée au centre vaut un fou.',
      'Les pions ne reculent pas. Pensez-y avant de les pousser.',
    ],
    finale: [
      'En finale, le roi marche vers le centre.',
      'Un pion passé doit être soutenu, pas lancé seul.',
      'Les tours se placent derrière les pions passés.',
      'Comptez les coups avant de pousser. C’est de l’arithmétique.',
      'Gardez vos pions reliés, c’est tout ce qui tient.',
      'En finale, une case gagnée ne se rend plus.',
      'Activez la tour avant de défendre le pion.',
      'Le camp qui a le roi le plus actif gagne souvent.',
      'Simplifiez vers une finale que vous savez tenir.',
      'Les finales de pions se calculent, elles ne se sentent pas.',
      'Un pion de plus sur l’aile où il est seul vaut deux ailleurs.',
      'Échangez les pièces, gardez les pions : c’est la règle quand vous êtes devant.',
    ],
  },
  johana: {
    ouverture: [
      'Au début, on sort les pièces et on met le roi à l’abri. C’est tout.',
      'Ne bougez pas deux fois la même pièce dans l’ouverture.',
      'La dame reste à la maison au début, elle se ferait courser.',
      'Prenez le centre, c’est là que tout passe.',
      'Roquez tôt, vous dormirez mieux.',
      'Un coup, une pièce développée. Simple.',
      'Évitez de pousser trop de pions, ça laisse des trous.',
      'Regardez ce que l’adversaire menace à chaque coup.',
      'Le cavalier aime le centre, le fou aime les longues diagonales.',
      'Si vous ne savez pas quoi jouer, développez.',
      'Les tours sortent en dernier, mais elles sortent.',
      'Ne cherchez pas le piège, cherchez le bon coup.',
    ],
    milieu: [
      'Au milieu, demandez-vous : qu’est-ce qu’il veut faire, lui ?',
      'Comptez les pièces qui attaquent et celles qui défendent.',
      'Une pièce qui ne fait rien, c’est une pièce à déplacer.',
      'Cherchez les pièces adverses mal protégées.',
      'Avant d’attaquer, vérifiez votre roi.',
      'Ne donnez rien gratuitement, même pour un beau coup.',
      'Les tours sur les colonnes ouvertes, toujours.',
      'Si vous voyez une fourchette, cherchez-en une autre.',
      'Un plan simple bien joué vaut mieux qu’un plan génial raté.',
      'Prenez le temps de regarder tout l’échiquier.',
      'Quand ça se complique, comptez le matériel.',
      'Un coup qui améliore une pièce est toujours un bon coup.',
    ],
    finale: [
      'En finale, votre roi devient un attaquant. Faites-le avancer.',
      'Un pion passé, c’est de l’or. Poussez-le.',
      'Les tours se mettent derrière les pions.',
      'Comptez les cases, c’est de l’arithmétique.',
      'Gardez vos pions ensemble, ils se protègent.',
      'Ne laissez pas votre roi au fond, il s’ennuie.',
      'En finale, un tempo peut tout changer.',
      'Échangez les pièces si vous avez un pion de plus.',
      'Si vous êtes en moins, cherchez la nulle, pas le miracle.',
      'La patience gagne les finales.',
      'Deux pions reliés valent souvent une pièce.',
      'Avancez le roi avant de pousser le pion.',
    ],
  },
  serena: {
    ouverture: [
      'L’ouverture est la partie du jeu la plus écrite, et la moins comprise.',
      'On a nommé ces débuts d’après des villes, des joueurs, des hasards.',
      'Développez : c’est le seul conseil d’ouverture qui ait survécu à trois siècles.',
      'Au dix-neuvième siècle on sacrifiait tout dès le quatrième coup. On a mûri.',
      'Le centre, ce vieux débat : l’occuper, ou le contrôler ?',
      'Les hypermodernes vous diraient de laisser l’adversaire prendre le centre.',
      'Mettez votre roi à l’abri. C’est ce que Steinitz reprochait à tout le monde.',
      'Chaque coup d’ouverture est une promesse. Tenez-la.',
      'Une pièce bien placée en ouverture travaille pour vous tout le reste.',
      'On a joué cette position des milliers de fois. Ajoutez-y quelque chose.',
      'Les noms d’ouvertures sont de la géographie, pas de la stratégie.',
      'Philidor disait déjà que les pions sont l’âme du jeu. Il parlait de l’ouverture.',
    ],
    milieu: [
      'Le milieu de partie, c’est là que le jeu devient vous.',
      'Nimzowitsch disait de bloquer avant d’attaquer. Il avait souvent raison.',
      'Cherchez le défaut de la position adverse. Il y en a toujours un.',
      'Une bonne position, c’est une position où vos pièces se parlent.',
      'Les colonnes ouvertes sont des avenues. Mettez-y vos tours.',
      'Le plus difficile est de trouver le plan, non le coup.',
      'Améliorez votre pièce la plus triste. Petrossian en avait fait une règle.',
      'Avant l’attaque, comptez. L’enthousiasme coûte cher.',
      'Une faiblesse fixe vaut mieux qu’une attaque floue.',
      'Regardez la position comme un tableau, puis comme une équation.',
      'Tarrasch voulait de l’espace, Steinitz voulait des faiblesses. Les deux marchent.',
      'On manœuvre pour améliorer, pas pour attendre.',
    ],
    finale: [
      'En finale, le jeu redevient de l’arithmétique, et c’est beau.',
      'Le roi sort enfin de sa boîte. Laissez-le marcher.',
      'Un pion passé lointain vaut parfois une pièce.',
      'Philidor et Lucena ont laissé leurs noms à des positions que vous rencontrerez.',
      'Les tours derrière les pions : Tarrasch en avait fait une loi.',
      'En finale, un tempo pèse plus qu’une pièce en ouverture.',
      'La technique remplace l’inspiration. C’est reposant.',
      'Capablanca gagnait ses finales sans jamais paraître y toucher.',
      'Simplifiez vers ce que vous savez tenir, pas vers ce qui brille.',
      'Comptez, recomptez, puis poussez.',
      'Une finale de pions est une question fermée : il y a une réponse.',
      'Le roi actif en finale vaut davantage qu’un pion de plus.',
    ],
  },
};
